plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url "https://cursemaven.com" }
    maven { url "https://api.modrinth.com/maven" }
    maven { url "https://maven.caffeinemc.net/releases" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
//    compileOnly "maven.modrinth:sodium:mc1.21.1-0.8.13-beta.2-neoforge"
    // For some reason 'Sodium' is considered a non-minecraft library due to the weird jar-in-jar setup
    // See https://docs.neoforged.net/toolchain/docs/dependencies/nonmclibs/
//    additionalRuntimeClasspath "maven.modrinth:sodium:mc1.21.1-0.8.13-beta.2-neoforge"
    // Jar-in-jar setup from the whole mod prevents the source from being available
    compileOnly "net.caffeinemc:sodium-neoforge-mod:0.8.13-beta.2+mc1.21.1"

    // https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=show
    compileOnly "curse.maven:irisshaders-455508:8242804" // 1.8.14 Beta 1

    // Bumblezone
    // https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=show
//    implementation "curse.maven:the-bumblezone-forge-362479:8548224" // v7.15.3
    // https://www.curseforge.com/minecraft/mc-mods/resourceful-lib/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=show
    compileOnly "curse.maven:resourceful-lib-570073:5973188" // 3.0.12

    // Create
    compileOnly "maven.modrinth:create:6.0.10+mc1.21.1"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
